services:
  db:
    image: postgres:15-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    image: ecommerceapi-api
    container_name: ecommerce_api
    ports:
      - "8080:8088"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=ecommerce;Username=postgres;Password=P@ssw0rd"
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8088"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
